-- AlterTable
ALTER TABLE "Config" ADD COLUMN     "defaultRatePT" DOUBLE PRECISION NOT NULL DEFAULT 45475,
ADD COLUMN     "ftDivisor" DOUBLE PRECISION NOT NULL DEFAULT 173;

-- AlterTable
ALTER TABLE "Staff" ADD COLUMN     "gajiBulanan" DOUBLE PRECISION,
ADD COLUMN     "namaLengkap" TEXT,
ADD COLUMN     "rateHourly" DOUBLE PRECISION;
